export const componentData = {
  gpu: {
    name: 'Graphics Card (GPU)',
    icon: 'gpu',
    description: 'Handles graphics rendering and visual processing for games, 3D applications, and GPU-accelerated workloads. Modern GPUs have thousands of cores optimized for parallel computation.',
    specs: ['VRAM: 8GB–24GB GDDR6X', 'CUDA Cores / Stream Processors', 'Ray Tracing & DLSS support', 'PCIe 4.0/5.0 x16 interface', 'DisplayPort & HDMI outputs'],
    tips: 'Match your GPU to your monitor resolution. For 1440p gaming, 12GB+ VRAM is recommended.',
    color: '#1a1a2e',
    accent: '#e94560',
    connections: ['Motherboard → PCIe x16 slot', 'PSU → PCIe power cables', 'Display → Monitor'],
  },
  cpu: {
    name: 'Processor (CPU)',
    icon: 'cpu',
    description: 'The main processing unit of the computer. It executes instructions and coordinates system operations. Modern CPUs have multiple cores for simultaneous task handling.',
    specs: ['Cores & Threads (e.g., 8C/16T)', 'Clock Speed: Base & Boost (GHz)', 'L1/L2/L3 Cache memory', 'Socket: LGA1700 / AM5', 'TDP: 65W–170W'],
    tips: 'For gaming, prioritize single-core speed. For rendering and content creation, more cores deliver better multi-threaded performance.',
    color: '#4a5568',
    accent: '#a0aec0',
    connections: ['Motherboard → CPU socket', 'AIO Cooler → CPU IHS', 'RAM → Memory controller'],
  },
  ram: {
    name: 'System Memory (RAM)',
    icon: 'ram',
    description: 'High-speed temporary memory used by the CPU to store actively running data and applications. More RAM allows more programs to run simultaneously without slowdown.',
    specs: ['Capacity: 16GB, 32GB, 64GB', 'Type: DDR4 3200MHz / DDR5 6000MHz', 'CAS Latency (CL) — lower is faster', 'Dual-Channel configuration', 'XMP / EXPO profiles'],
    tips: '16GB is the minimum for modern gaming. 32GB is ideal for streaming, video editing, and heavy multitasking.',
    color: '#1e3a5f',
    accent: '#60a5fa',
    connections: ['Motherboard → DIMM slots', 'CPU → Memory controller'],
  },
  motherboard: {
    name: 'Motherboard',
    icon: 'motherboard',
    description: 'The central circuit board that connects the CPU, memory, storage, GPU, power delivery, and all other system components. It is the backbone of the PC.',
    specs: ['Form factor: ATX / Micro-ATX', 'Chipset: Z790 / B650', 'PCIe 5.0 x16 slot', '4x DIMM slots (DDR5)', 'M.2 NVMe, SATA, USB ports'],
    tips: 'Choose a motherboard with the correct CPU socket and enough expansion slots for your future upgrade plans.',
    color: '#2d6a1e',
    accent: '#4ade80',
    connections: ['CPU ↔ Socket', 'RAM ↔ DIMM slots', 'GPU ↔ PCIe slot', 'Storage ↔ M.2/SATA', 'PSU ↔ 24-pin + EPS'],
  },
  psu: {
    name: 'Power Supply (PSU)',
    icon: 'psu',
    description: 'Converts AC power from the wall outlet into regulated DC power required by the PC\'s internal components. Distributes power through modular cables.',
    specs: ['Wattage: 650W–1000W+', '80 Plus Gold / Platinum rating', 'Fully modular cables', 'Protection: OVP, OCP, SCP, OTP', 'ATX 3.0 / PCIe 5.0 ready'],
    tips: 'Always leave 20–30% headroom. A 750W PSU for a 550W system gives safety margin and room for future upgrades.',
    color: '#1a1a1a',
    accent: '#fbbf24',
    connections: ['Motherboard → 24-pin ATX', 'CPU → 8-pin EPS', 'GPU → PCIe power', 'Storage → SATA power'],
  },
  storage: {
    name: 'NVMe Storage (SSD)',
    icon: 'storage',
    description: 'High-speed solid-state storage used for the operating system, applications, games, and files. NVMe drives are significantly faster than traditional SATA SSDs.',
    specs: ['NVMe M.2 PCIe 4.0/5.0', 'Capacities: 256GB–4TB', 'Read speeds up to 7,000 MB/s', 'Form factor: M.2 2280', '3D NAND flash technology'],
    tips: 'Use a fast NVMe SSD for your OS and frequently-used programs. Add a secondary SSD or HDD for bulk media storage.',
    color: '#2d3748',
    accent: '#a78bfa',
    connections: ['Motherboard → M.2 slot', 'Chipset → PCIe lanes'],
  },
  cooler: {
    name: 'Liquid CPU Cooler (AIO)',
    icon: 'cooler',
    description: 'Transfers heat away from the CPU through a liquid cooling loop and radiator. More efficient than air cooling for high-TDP processors.',
    specs: ['Radiator size: 240mm / 360mm', 'Pump speed & noise level', 'Copper cold plate', 'Sleeved tubing', 'RGB pump cap'],
    tips: 'A 240mm AIO handles most CPUs well. For overclocked i7/i9 or Ryzen 9, a 360mm radiator is recommended.',
    color: '#1a1a2e',
    accent: '#8b5cf6',
    connections: ['CPU → Pump block', 'Radiator → Top mount', 'Fans → Radiator', 'Motherboard → Pump header'],
  },
  radiator: {
    name: 'AIO Radiator',
    icon: 'radiator',
    description: 'Releases heat from the liquid coolant into the surrounding airflow. Mounted at the top of the case with fans pushing air through the fin array.',
    specs: ['360mm aluminum radiator', 'High-density fin stack', 'Dual 120mm fans', 'G1/4 threaded fittings', 'Sleeved tubing connections'],
    tips: 'Top-mount as exhaust is the optimal configuration — it uses natural convection and prevents air bubbles from reaching the pump.',
    color: '#c4c6ca',
    accent: '#8b5cf6',
    connections: ['AIO Pump → Tubing', 'Fans → Radiator body', 'Case → Top mounting bracket'],
  },
  fans: {
    name: 'Cooling Fans',
    icon: 'fans',
    description: 'Move air through the chassis to maintain appropriate temperatures for all internal components. RGB fans add customizable lighting effects.',
    specs: ['120mm / 140mm size', 'PWM speed control', 'RGB: Addressable LEDs', 'Airflow: 40–70 CFM', 'Hydro / rifle bearing'],
    tips: 'Front intake + top/rear exhaust creates positive pressure, which reduces dust buildup inside the case.',
    color: '#1a1a1a',
    accent: '#22d3ee',
    connections: ['Motherboard → Fan headers', 'RGB Controller → ARGB header', 'Case → Mounting points'],
  },
};

// Focus positions for each component (world coords, relative to case)
export const componentFocus = {
  gpu:         { pos: [-3.5, 0.2, -0.4], target: [-1.5, 0.1, -0.4] },
  cpu:         { pos: [-3.2, 0.4, -0.3], target: [0.1, 0.35, -0.4] },
  ram:         { pos: [-3.5, 0.55, -0.5], target: [1.0, 0.55, -0.8] },
  motherboard: { pos: [-3.5, 0.4, 1.0],  target: [0.3, 0.4, 0.5] },
  psu:         { pos: [-3.5, -1.5, 0.8],  target: [0.7, -2.1, 0.2] },
  storage:     { pos: [-3.5, 0.2, 1.2],   target: [0.5, 0.2, 1.0] },
  cooler:      { pos: [-3.2, 0.4, -0.3],  target: [0.1, 0.35, -0.4] },
  radiator:    { pos: [-3.5, 2.4, 0],     target: [0, 2.2, 0] },
  fans:        { pos: [-3.5, 1.6, 1.8],   target: [0, 1.6, 1.2] },
};
