export const componentData = {
  motherboard: {
    name: 'Motherboard',
    description: 'The motherboard is the main circuit board that connects all components together. It acts as the central nervous system of the PC, allowing the CPU, RAM, GPU, and storage to communicate with each other.',
    specs: ['Form factors: ATX, Micro-ATX, Mini-ITX', 'Chipset determines features and compatibility', 'PCIe slots for expansion cards', 'RAM slots (DIMM)', 'SATA & M.2 connectors'],
    tips: 'When choosing a motherboard, match the socket type to your CPU and ensure it has enough ports for your needs.',
    color: '#2d6a1e',
    accent: '#4ade80',
  },
  cpu: {
    name: 'CPU (Processor)',
    description: 'The Central Processing Unit is the "brain" of the computer. It executes instructions from programs and performs calculations. Modern CPUs have multiple cores that can handle tasks simultaneously.',
    specs: ['Cores & threads (e.g., 8 cores / 16 threads)', 'Clock speed measured in GHz', 'Cache memory (L1, L2, L3)', 'Socket type (e.g., LGA1700, AM5)', 'TDP (Thermal Design Power) in Watts'],
    tips: 'For gaming, prioritize single-core performance. For video editing and rendering, more cores are better.',
    color: '#4a5568',
    accent: '#a0aec0',
  },
  ram: {
    name: 'RAM (Memory)',
    description: 'Random Access Memory is the short-term memory of the PC. It stores data that the CPU needs quick access to. More RAM lets you run more applications simultaneously without slowdown.',
    specs: ['Capacity: 8GB, 16GB, 32GB, 64GB', 'Type: DDR4, DDR5', 'Speed measured in MHz (e.g., 3200MHz)', 'CAS Latency (CL) — lower is faster', 'Dual-channel vs single-channel'],
    tips: '16GB is the sweet spot for most users. 32GB is recommended for heavy multitasking or content creation.',
    color: '#1e3a5f',
    accent: '#60a5fa',
  },
  gpu: {
    name: 'GPU (Graphics Card)',
    description: 'The Graphics Processing Unit renders images, videos, and animations. It has thousands of small cores designed for parallel processing. Essential for gaming, 3D rendering, and AI workloads.',
    specs: ['VRAM: 8GB, 12GB, 16GB, 24GB', 'CUDA Cores / Stream Processors', 'Core clock & boost clock', 'Ray tracing cores (RTX)', 'Power connectors (6-pin, 8-pin)'],
    tips: 'Match your GPU to your monitor resolution. 1440p gaming needs more VRAM than 1080p.',
    color: '#1a1a2e',
    accent: '#e94560',
  },
  psu: {
    name: 'PSU (Power Supply)',
    description: 'The Power Supply Unit converts AC power from the wall outlet into DC power that PC components can use. It distributes power through cables to the motherboard, CPU, GPU, and drives.',
    specs: ['Wattage: 500W, 650W, 750W, 1000W+', '80 Plus rating: Bronze, Silver, Gold, Platinum', 'Modular vs non-modular cables', 'ATX, SFX form factors', 'Protection: OVP, OCP, SCP, OTP'],
    tips: 'Always leave headroom — a 650W PSU for a 500W system gives you safety margin and upgrade room.',
    color: '#1a1a1a',
    accent: '#fbbf24',
  },
  storage: {
    name: 'Storage (SSD / HDD)',
    description: 'Storage drives hold your operating system, programs, and files permanently. SSDs are much faster than HDDs. NVMe M.2 SSDs are the fastest consumer storage available today.',
    specs: ['SSD: NVMe M.2, SATA SSD', 'HDD: 7200 RPM, 5400 RPM', 'Capacities: 256GB to 4TB+', 'Read/Write speeds: up to 7000 MB/s (NVMe)', 'Form factors: 2.5", M.2 2280, 3.5"'],
    tips: 'Use an NVMe SSD for your OS and frequently used programs. Use an HDD for bulk media storage.',
    color: '#2d3748',
    accent: '#a78bfa',
  },
};
